"""
audit_supplemental_v2.py — Tier-A label-noise auditor for supplemental_dogs/.

Flags images where the model is high-confidence-wrong about the labeled breed,
moves them (recoverable) to supplemental_dogs_quarantine_v2/<folder>/<file>.

Cluster-aware: same-cluster predictions never flag (e.g. an image in
working_kelpie/ predicted as "Australian Kelpie" is fine because they are
in the same synonym cluster).

Usage:
    python outputs/audit_supplemental_v2.py baseline              # measure baseline (no moves)
    python outputs/audit_supplemental_v2.py sanity --folder akita # audit one folder, no moves
    python outputs/audit_supplemental_v2.py audit                 # full sweep (executes moves)
    python outputs/audit_supplemental_v2.py audit --folder akita  # one folder + execute
    python outputs/audit_supplemental_v2.py post                  # post-audit measurement + decision
    python outputs/audit_supplemental_v2.py rollback              # restore all quarantined files
    python outputs/audit_supplemental_v2.py status                # print manifest summary

Outputs in outputs/audit_v2/:
    baseline_metrics.json   — 3-seed baseline metrics (top-1, top-3, rejected)
    post_metrics.json       — same shape, after audit
    quarantine_manifest.jsonl — append-only record of all moved files
    audit_progress.json     — live progress during full sweep
    per_folder_stats.json   — per-folder breakdown
    REPORT.md / SUCCESS.md / REGRESSION.md / MARGINAL.md — generated by `post`
"""
import argparse
import json
import os
import shutil
import sys
import time
from datetime import datetime
from pathlib import Path

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

# Make harness importable
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))
import test_20_images as t  # noqa: E402

import numpy as np  # noqa: E402
from PIL import Image  # noqa: E402
import tensorflow as tf  # noqa: E402

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────
QUARANTINE_DIR = ROOT / "supplemental_dogs_quarantine_v2"
AUDIT_OUT = ROOT / "outputs" / "audit_v2"
MANIFEST_PATH = AUDIT_OUT / "quarantine_manifest.jsonl"
PROGRESS_PATH = AUDIT_OUT / "audit_progress.json"
BASELINE_PATH = AUDIT_OUT / "baseline_metrics.json"
POST_PATH = AUDIT_OUT / "post_metrics.json"
PER_FOLDER_PATH = AUDIT_OUT / "per_folder_stats.json"

# Tier-A thresholds
DIFFERENT_BREED_THRESHOLD = 0.40   # top-1 prediction confidence floor for "high conf"
OWN_CLUSTER_LOW_THRESHOLD = 0.05   # truth-cluster confidence ceiling for "low own"
MIN_KEEP_PER_FOLDER = 50           # never quarantine if it would leave < this many
SEEDS_FOR_HARNESS = [43, 100, 200] # post-paths for random_sample (seed = RANDOM_SEED + 1)
                                   # so we set t.RANDOM_SEED to these - 1: [42, 99, 199]

# Keras inference config (GPU batched)
KERAS_INPUT_SIZE = 300
NUM_CLASSES = 296
WEIGHTS_PATH = ROOT / "tf_cache" / "best_weights_continue.weights.h5"
BATCH_SIZE = 32                    # internal Keras batch size
CHUNK_IMAGES_PER_FOLDER = 64       # process this many images' TTA variants per predict call
                                   # -> 64 * 3 = 192 variants, batched 32-at-a-time by Keras

AUDIT_OUT.mkdir(parents=True, exist_ok=True)
QUARANTINE_DIR.mkdir(parents=True, exist_ok=True)


# ─────────────────────────────────────────────────────────────────────────────
# Model + label loading (once per process)
# ─────────────────────────────────────────────────────────────────────────────
def load_model():
    """Rebuild the v6 Keras architecture and load best_weights_continue.

    Architecture mirrors export_tflite.py exactly so weights load without
    shape/name mismatches.
    """
    tf.keras.mixed_precision.set_global_policy("float32")
    base = tf.keras.applications.EfficientNetV2S(
        input_shape=(KERAS_INPUT_SIZE, KERAS_INPUT_SIZE, 3),
        include_top=False,
        weights=None,  # we'll load from the checkpoint
    )
    base.trainable = True
    features = base.output
    gap = tf.keras.layers.GlobalAveragePooling2D(name="gap")(features)
    gmp = tf.keras.layers.GlobalMaxPooling2D(name="gmp")(features)
    bilinear = tf.keras.layers.Multiply(name="bilinear_mul")([gap, gmp])
    bilinear = tf.keras.layers.BatchNormalization(name="bilinear_bn")(bilinear)
    merged = tf.keras.layers.Concatenate(name="merge_features")([gap, bilinear])
    x = tf.keras.layers.Dropout(0.4)(merged)
    x = tf.keras.layers.Dense(512, activation="relu", name="fc1")(x)
    x = tf.keras.layers.Dropout(0.3)(x)
    x = tf.keras.layers.Dense(256, activation="relu", name="fc2")(x)
    x = tf.keras.layers.Dropout(0.2)(x)
    out = tf.keras.layers.Dense(NUM_CLASSES, activation="softmax", name="predictions")(x)
    model = tf.keras.Model(inputs=base.input, outputs=out)
    if not WEIGHTS_PATH.exists():
        raise SystemExit(f"Missing weights: {WEIGHTS_PATH}")
    model.load_weights(str(WEIGHTS_PATH))
    return model


def load_assets():
    labels = [ln.strip() for ln in t.LABELS_PATH.read_text(encoding="utf-8").splitlines() if ln.strip()]
    label_to_idx = {ln: i for i, ln in enumerate(labels)}
    dogs = json.loads(t.DOGS_JSON_PATH.read_text(encoding="utf-8"))
    dog_index = {d["name"]: d for d in dogs}
    return labels, label_to_idx, dogs, dog_index


def get_cluster_members(name: str) -> list:
    for cluster in t.SYNONYM_CLUSTERS:
        if name in cluster:
            return cluster
    return [name]


def folder_to_breed_resolved(folder: str, dog_index: dict) -> str | None:
    """Resolve folder name → canonical Dog.name in dogs.json, or None."""
    guess = t.folder_to_breed(folder)
    for cand in [guess, guess.replace(" Dog", ""), "American " + guess]:
        if cand in dog_index:
            return cand
    for name in dog_index:
        if name.lower() == guess.lower():
            return name
    return None


# ─────────────────────────────────────────────────────────────────────────────
# Inference (3-variant TTA, Keras batched on GPU)
# ─────────────────────────────────────────────────────────────────────────────
def infer_batch_tta(model, pil_images: list) -> np.ndarray:
    """Accept a list of PIL images, return (N, NUM_CLASSES) probs.

    Each image is expanded to 3 TTA variants (tight center / flip / loose),
    all are batched into one model.predict call at BATCH_SIZE, results are
    reshaped and averaged across the 3 variants per image.
    """
    n = len(pil_images)
    if n == 0:
        return np.empty((0, NUM_CLASSES), dtype=np.float32)
    all_variants = []
    for img in pil_images:
        variants = t.build_3variant_tta(img)  # 3 uint8 arrays (300, 300, 3)
        all_variants.extend(variants)
    batch = np.stack(all_variants, axis=0).astype(np.float32)  # (3N, 300, 300, 3)
    probs = model.predict(batch, batch_size=BATCH_SIZE, verbose=0)  # (3N, 296)
    probs = probs.reshape(n, 3, NUM_CLASSES).mean(axis=1)  # (N, 296)
    return probs.astype(np.float32)


def infer_single_tta(model, img_path: Path) -> np.ndarray | None:
    try:
        img = Image.open(img_path)
        img.load()
    except Exception:
        return None
    return infer_batch_tta(model, [img])[0]


# ─────────────────────────────────────────────────────────────────────────────
# Baseline measurement (3 seeds, random_sample mode)
# ─────────────────────────────────────────────────────────────────────────────
def measure_baseline(model, labels, dogs, dog_index, seeds=SEEDS_FOR_HARNESS):
    """Run 3-seed random_sample harness; return list of per-seed dicts.

    Uses Keras batched inference — each seed's 20-image sample is processed
    in a single predict call (60 TTA variants, batched 32-at-a-time internally).
    """
    results = []
    for seed in seeds:
        # random_sample uses random.Random(RANDOM_SEED + 1); to get effective seed=N we set RANDOM_SEED=N-1
        original_seed = t.RANDOM_SEED
        t.RANDOM_SEED = seed - 1
        try:
            sample = t.random_sample(dogs, t.SUPPLEMENTAL_DIR, n=20)
        finally:
            t.RANDOM_SEED = original_seed

        # Load all sample images up front, then batch-infer
        sample_pil = []
        sample_valid_idx = []
        for i, item in enumerate(sample):
            try:
                im = Image.open(item["image"])
                im.load()
                sample_pil.append(im)
                sample_valid_idx.append(i)
            except Exception:
                pass
        probs_batch = infer_batch_tta(model, sample_pil) if sample_pil else np.empty((0, NUM_CLASSES))

        correct1 = correct3 = rejected = 0
        per_image = []
        probs_lookup = {valid_i: probs_batch[k] for k, valid_i in enumerate(sample_valid_idx)}
        for i, item in enumerate(sample):
            truth_cluster = t.cluster_key(item["breed"])
            if i not in probs_lookup:
                per_image.append({"image": str(item["image"]), "error": "open_failed"})
                continue
            probs = probs_lookup[i]
            res = t.build_results(probs, labels, dog_index)
            if res["rejected"]:
                rejected += 1
                per_image.append({"image": item["image"].name, "rejected": res["rejected"]})
                continue
            top1 = res["accepted"][0]["displayed_name"] if res["accepted"] else "(none)"
            displayed = [a["displayed_name"] for a in res["accepted"]]
            hit1 = top1 == truth_cluster
            hit3 = truth_cluster in displayed
            if hit1: correct1 += 1
            if hit3: correct3 += 1
            per_image.append({
                "image": item["image"].name, "truth": item["breed"],
                "displayed_top1": top1, "top1_hit": hit1, "top3_hit": hit3,
            })
        n = sum(1 for p in per_image if "error" not in p and "rejected" not in p) + rejected
        n_scored = sum(1 for p in per_image if "error" not in p and "rejected" not in p)
        results.append({
            "seed": seed,
            "n_total": len(sample),
            "n_scored": n_scored,
            "rejected": rejected,
            "top1_correct": correct1,
            "top3_correct": correct3,
            "top1_pct": (correct1 / n_scored * 100.0) if n_scored else 0.0,
            "top3_pct": (correct3 / n_scored * 100.0) if n_scored else 0.0,
            "per_image": per_image,
        })
        print(f"  seed={seed}: top-1={correct1}/{n_scored} ({results[-1]['top1_pct']:.1f}%), "
              f"top-3={correct3}/{n_scored} ({results[-1]['top3_pct']:.1f}%), rejected={rejected}")
    return results


def average_metrics(results: list) -> dict:
    if not results:
        return {"top1_pct": 0.0, "top3_pct": 0.0, "n_seeds": 0}
    return {
        "top1_pct": sum(r["top1_pct"] for r in results) / len(results),
        "top3_pct": sum(r["top3_pct"] for r in results) / len(results),
        "n_seeds": len(results),
    }


# ─────────────────────────────────────────────────────────────────────────────
# Folder audit (Tier-A: high-conf-wrong + low-own-conf)
# ─────────────────────────────────────────────────────────────────────────────
def list_image_files(folder_path: Path) -> list:
    return sorted(p for p in folder_path.iterdir()
                  if p.is_file() and p.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp"})


def already_quarantined() -> set:
    """Return set of source-path strings already in the manifest (idempotency)."""
    if not MANIFEST_PATH.exists():
        return set()
    seen = set()
    for line in MANIFEST_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            rec = json.loads(line)
            seen.add(rec["src"])
        except Exception:
            continue
    return seen


def audit_folder(model, labels, label_to_idx, dog_index,
                 folder_path: Path, dry_run: bool, quarantined_set: set) -> dict:
    """
    Audit a single folder. Return {folder, n, n_skipped, n_audited, n_flagged, flags}.
    `flags` is a list of dicts; if dry_run=False, flagged images are moved.

    Uses Keras batched inference — images are processed in chunks of
    CHUNK_IMAGES_PER_FOLDER at a time to cap GPU memory.
    """
    folder = folder_path.name
    truth_breed = folder_to_breed_resolved(folder, dog_index)
    images = list_image_files(folder_path)

    if truth_breed is None:
        return {"folder": folder, "skipped_reason": "no dogs.json match",
                "n": len(images), "n_audited": 0, "n_flagged": 0, "flags": []}
    if folder in t.FLAGGED_FOLDERS:
        return {"folder": folder, "skipped_reason": "in FLAGGED_FOLDERS",
                "n": len(images), "n_audited": 0, "n_flagged": 0, "flags": []}

    truth_cluster = t.cluster_key(truth_breed)
    cluster_members = get_cluster_members(truth_cluster)
    own_idxs = [label_to_idx[m] for m in cluster_members if m in label_to_idx]

    # Filter already-quarantined
    audit_list = [p for p in images if str(p) not in quarantined_set]
    n_skipped_already = len(images) - len(audit_list)
    n_audited = len(audit_list)

    # Batch through the folder
    flags = []
    for i in range(0, len(audit_list), CHUNK_IMAGES_PER_FOLDER):
        chunk_paths = audit_list[i:i + CHUNK_IMAGES_PER_FOLDER]
        pil_imgs = []
        valid_paths = []
        for p in chunk_paths:
            try:
                im = Image.open(p)
                im.load()
                pil_imgs.append(im)
                valid_paths.append(p)
            except Exception:
                continue
        if not pil_imgs:
            continue
        probs_batch = infer_batch_tta(model, pil_imgs)  # (K, 296)
        for k, img_path in enumerate(valid_paths):
            probs = probs_batch[k]
            top_idx = int(np.argmax(probs))
            top_label = labels[top_idx]
            top_conf = float(probs[top_idx])
            top_cluster = t.cluster_key(top_label)
            own_conf = float(sum(probs[j] for j in own_idxs))

            # Cluster-aware: same-cluster predictions NEVER flag
            if top_cluster == truth_cluster:
                continue
            # Tier-A: high-conf-wrong + low-own-conf
            if top_conf >= DIFFERENT_BREED_THRESHOLD and own_conf < OWN_CLUSTER_LOW_THRESHOLD:
                flags.append({
                    "src": str(img_path),
                    "folder": folder,
                    "truth_cluster": truth_cluster,
                    "top_label": top_label,
                    "top_cluster": top_cluster,
                    "top_conf": top_conf,
                    "own_conf": own_conf,
                })

    # MIN_KEEP=50 floor: don't drop folder below this
    n_total = len(images)
    n_already_q = n_skipped_already
    keepable = n_total - n_already_q
    max_can_remove = max(0, keepable - MIN_KEEP_PER_FOLDER)
    if len(flags) > max_can_remove:
        # Sort by most-suspicious-first: high top_conf first, low own_conf first
        flags.sort(key=lambda f: (-f["top_conf"], f["own_conf"]))
        kept_flags = flags[:max_can_remove]
        flags = kept_flags

    if not dry_run:
        for f in flags:
            src = Path(f["src"])
            dst = QUARANTINE_DIR / folder / src.name
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(src), str(dst))
            f["dst"] = str(dst)
            f["timestamp"] = datetime.utcnow().isoformat() + "Z"
            with MANIFEST_PATH.open("a", encoding="utf-8") as mf:
                mf.write(json.dumps(f) + "\n")

    return {
        "folder": folder, "n": n_total, "n_audited": n_audited,
        "n_skipped_already_quarantined": n_skipped_already,
        "n_flagged": len(flags),
        "n_capped_by_min_keep": max(0, n_audited - max_can_remove) if False else 0,
        "truth_cluster": truth_cluster,
        "flags": flags,
    }


def list_audit_folders(supplemental: Path, dog_index: dict) -> list:
    """All non-flagged folders that resolve to a Dog.name."""
    out = []
    for p in sorted(supplemental.iterdir()):
        if not p.is_dir():
            continue
        if p.name in t.FLAGGED_FOLDERS:
            continue
        if folder_to_breed_resolved(p.name, dog_index) is None:
            continue
        out.append(p)
    return out


def write_progress(payload: dict):
    PROGRESS_PATH.write_text(json.dumps(payload, indent=2), encoding="utf-8")


# ─────────────────────────────────────────────────────────────────────────────
# Rollback
# ─────────────────────────────────────────────────────────────────────────────
def rollback_all() -> int:
    if not MANIFEST_PATH.exists():
        print("No manifest found; nothing to roll back.")
        return 0
    n = 0
    for line in MANIFEST_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            rec = json.loads(line)
        except Exception:
            continue
        src, dst = Path(rec["src"]), Path(rec.get("dst", ""))
        if dst and dst.exists() and not src.exists():
            src.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(dst), str(src))
            n += 1
    # Archive the manifest so subsequent re-runs don't double-restore
    archive = MANIFEST_PATH.with_suffix(".jsonl." + datetime.utcnow().strftime("%Y%m%dT%H%M%S") + ".rolledback")
    MANIFEST_PATH.rename(archive)
    print(f"Rolled back {n} files; manifest archived to {archive.name}")
    return n


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────
def cmd_baseline(args):
    model = load_model()
    labels, label_to_idx, dogs, dog_index = load_assets()
    print(f"Measuring baseline (3 seeds: {SEEDS_FOR_HARNESS})...")
    results = measure_baseline(model, labels, dogs, dog_index)
    avg = average_metrics(results)
    payload = {
        "measured_at": datetime.utcnow().isoformat() + "Z",
        "seeds": SEEDS_FOR_HARNESS,
        "per_seed": results,
        "average": avg,
    }
    BASELINE_PATH.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")
    print(f"\nBaseline written: avg top-1 = {avg['top1_pct']:.1f}%, avg top-3 = {avg['top3_pct']:.1f}%")
    print(f"Saved to: {BASELINE_PATH}")


def cmd_sanity(args):
    """One-folder dry run, prints the flags but does NOT move files."""
    model = load_model()
    labels, label_to_idx, dogs, dog_index = load_assets()
    folder_path = t.SUPPLEMENTAL_DIR / args.folder
    if not folder_path.exists():
        print(f"ERROR: folder {folder_path} does not exist.")
        sys.exit(2)
    quarantined = already_quarantined()
    print(f"Sanity audit on {folder_path.name}/ (dry-run, no moves)...")
    t0 = time.time()
    res = audit_folder(model, labels, label_to_idx, dog_index,
                       folder_path, dry_run=True, quarantined_set=quarantined)
    dt = time.time() - t0
    print(f"\nFolder: {res['folder']}")
    print(f"  truth_cluster: {res.get('truth_cluster', 'N/A')}")
    print(f"  total images: {res['n']}, audited: {res['n_audited']}, "
          f"already_quarantined: {res.get('n_skipped_already_quarantined', 0)}")
    print(f"  flagged (after MIN_KEEP={MIN_KEEP_PER_FOLDER}): {res['n_flagged']}")
    print(f"  inference time: {dt:.1f}s ({dt/max(1, res['n_audited'])*1000:.0f}ms/img)")
    if res["flags"]:
        print(f"\nFirst {min(10, len(res['flags']))} flagged:")
        for f in res["flags"][:10]:
            print(f"    {Path(f['src']).name}: predicted '{f['top_cluster']}' @ {f['top_conf']:.1%}, "
                  f"own-cluster conf {f['own_conf']:.1%}")
    return res


def cmd_audit(args):
    """Full sweep (or single folder if --folder set). Executes moves."""
    model = load_model()
    labels, label_to_idx, dogs, dog_index = load_assets()
    quarantined = already_quarantined()

    if args.folder:
        folders = [t.SUPPLEMENTAL_DIR / args.folder]
        if not folders[0].exists():
            print(f"ERROR: folder {folders[0]} does not exist.")
            sys.exit(2)
    else:
        folders = list_audit_folders(t.SUPPLEMENTAL_DIR, dog_index)

    print(f"Auditing {len(folders)} folder(s); already-quarantined entries: {len(quarantined)}")
    per_folder = []
    total_flagged = 0
    t0 = time.time()
    for i, fp in enumerate(folders, 1):
        res = audit_folder(model, labels, label_to_idx, dog_index,
                           fp, dry_run=False, quarantined_set=quarantined)
        per_folder.append(res)
        total_flagged += res["n_flagged"]
        elapsed = time.time() - t0
        remaining = elapsed / i * (len(folders) - i)
        write_progress({
            "started": datetime.utcnow().isoformat() + "Z",
            "folders_total": len(folders),
            "folders_done": i,
            "current_folder": fp.name,
            "total_flagged_so_far": total_flagged,
            "elapsed_sec": elapsed,
            "eta_sec": remaining,
        })
        print(f"[{i:3}/{len(folders)}] {fp.name}: audited={res['n_audited']}, "
              f"flagged={res['n_flagged']} (running total: {total_flagged}) "
              f"[{elapsed/60:.1f}m elapsed, ETA {remaining/60:.1f}m]")

    PER_FOLDER_PATH.write_text(json.dumps(per_folder, indent=2, default=str), encoding="utf-8")
    print(f"\nAudit complete. Total flagged: {total_flagged}. Per-folder stats: {PER_FOLDER_PATH}")
    return per_folder


def cmd_post(args):
    """Re-measure with 3-seed harness, compare to baseline, write decision doc."""
    if not BASELINE_PATH.exists():
        print(f"ERROR: {BASELINE_PATH} not found. Run `baseline` first.")
        sys.exit(2)
    baseline = json.loads(BASELINE_PATH.read_text(encoding="utf-8"))

    model = load_model()
    labels, label_to_idx, dogs, dog_index = load_assets()
    print(f"Measuring post-audit metrics (3 seeds: {SEEDS_FOR_HARNESS})...")
    results = measure_baseline(model, labels, dogs, dog_index)
    avg_post = average_metrics(results)
    payload = {
        "measured_at": datetime.utcnow().isoformat() + "Z",
        "seeds": SEEDS_FOR_HARNESS,
        "per_seed": results,
        "average": avg_post,
    }
    POST_PATH.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")

    avg_pre = baseline["average"]
    delta_top1 = avg_post["top1_pct"] - avg_pre["top1_pct"]
    delta_top3 = avg_post["top3_pct"] - avg_pre["top3_pct"]
    print(f"\nBaseline:  top-1={avg_pre['top1_pct']:.1f}%  top-3={avg_pre['top3_pct']:.1f}%")
    print(f"Post:      top-1={avg_post['top1_pct']:.1f}%  top-3={avg_post['top3_pct']:.1f}%")
    print(f"Delta:     top-1={delta_top1:+.1f}pt  top-3={delta_top3:+.1f}pt")

    # Decision rule per task spec
    if delta_top1 >= -1.0:
        decision = "KEEP_SUCCESS"
        doc = AUDIT_OUT / "SUCCESS.md"
    elif delta_top1 < -2.0:
        decision = "ROLLBACK_REGRESSION"
        doc = AUDIT_OUT / "REGRESSION.md"
    else:
        decision = "KEEP_MARGINAL"
        doc = AUDIT_OUT / "MARGINAL.md"

    write_decision_doc(doc, decision, avg_pre, avg_post, baseline, payload)
    print(f"\nDecision: {decision}")
    print(f"Doc: {doc}")

    if decision == "ROLLBACK_REGRESSION":
        print("\nAuto-rollback engaged...")
        n = rollback_all()
        print(f"Restored {n} files.")

    return decision


def write_decision_doc(path: Path, decision: str, pre: dict, post: dict, base_payload: dict, post_payload: dict):
    delta1 = post["top1_pct"] - pre["top1_pct"]
    delta3 = post["top3_pct"] - pre["top3_pct"]
    title = {
        "KEEP_SUCCESS": "Audit v2 — SUCCESS (quarantine kept)",
        "ROLLBACK_REGRESSION": "Audit v2 — REGRESSION (auto-rollback engaged)",
        "KEEP_MARGINAL": "Audit v2 — MARGINAL (quarantine kept, flagged for review)",
    }[decision]
    lines = [
        f"# {title}",
        "",
        f"**Decision:** `{decision}`  ",
        f"**Baseline measured:** {base_payload['measured_at']}  ",
        f"**Post measured:** {post_payload['measured_at']}  ",
        f"**Seeds:** {SEEDS_FOR_HARNESS}",
        "",
        "## Headline",
        "",
        "| Metric | Baseline | Post | Delta |",
        "|---|---|---|---|",
        f"| Avg top-1 | {pre['top1_pct']:.2f}% | {post['top1_pct']:.2f}% | {delta1:+.2f}pt |",
        f"| Avg top-3 | {pre['top3_pct']:.2f}% | {post['top3_pct']:.2f}% | {delta3:+.2f}pt |",
        "",
        "## Per-seed",
        "",
        "| Seed | Baseline top-1 | Post top-1 | Δ | Baseline top-3 | Post top-3 | Δ |",
        "|---|---|---|---|---|---|---|",
    ]
    pre_seeds = {r["seed"]: r for r in base_payload["per_seed"]}
    post_seeds = {r["seed"]: r for r in post_payload["per_seed"]}
    for s in SEEDS_FOR_HARNESS:
        b, p = pre_seeds.get(s, {}), post_seeds.get(s, {})
        lines.append(
            f"| {s} | {b.get('top1_pct',0):.1f}% | {p.get('top1_pct',0):.1f}% | "
            f"{(p.get('top1_pct',0)-b.get('top1_pct',0)):+.1f}pt | "
            f"{b.get('top3_pct',0):.1f}% | {p.get('top3_pct',0):.1f}% | "
            f"{(p.get('top3_pct',0)-b.get('top3_pct',0)):+.1f}pt |"
        )
    lines += [
        "",
        "## Decision rule",
        "",
        f"- top-1 Δ ≥ −1.0 pt → KEEP_SUCCESS",
        f"- top-1 Δ < −2.0 pt → ROLLBACK_REGRESSION (auto)",
        f"- otherwise → KEEP_MARGINAL (flag for human review)",
        "",
        f"This run's top-1 Δ = {delta1:+.2f}pt → **{decision}**",
        "",
        "## Rollback hint",
        "",
        "```",
        "python outputs/audit_supplemental_v2.py rollback",
        "```",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def cmd_status(args):
    if not MANIFEST_PATH.exists():
        print("No manifest yet.")
        return
    by_folder = {}
    n_total = 0
    for line in MANIFEST_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            rec = json.loads(line)
        except Exception:
            continue
        n_total += 1
        by_folder.setdefault(rec["folder"], 0)
        by_folder[rec["folder"]] += 1
    print(f"Quarantine manifest: {n_total} files across {len(by_folder)} folders")
    for folder, n in sorted(by_folder.items(), key=lambda kv: -kv[1])[:20]:
        print(f"  {n:4}  {folder}")


def cmd_rollback(args):
    rollback_all()


def main():
    p = argparse.ArgumentParser(description=__doc__)
    sp = p.add_subparsers(dest="cmd", required=True)
    sp.add_parser("baseline", help="Measure 3-seed baseline metrics")
    sa = sp.add_parser("sanity", help="Audit a single folder (dry run)")
    sa.add_argument("--folder", required=True, help="folder name under supplemental_dogs/")
    au = sp.add_parser("audit", help="Execute audit + quarantine moves")
    au.add_argument("--folder", default=None, help="restrict to one folder (optional)")
    sp.add_parser("post", help="Re-measure + decide keep/rollback/marginal")
    sp.add_parser("rollback", help="Restore all quarantined files")
    sp.add_parser("status", help="Print manifest summary")
    args = p.parse_args()

    {
        "baseline": cmd_baseline,
        "sanity": cmd_sanity,
        "audit": cmd_audit,
        "post": cmd_post,
        "status": cmd_status,
        "rollback": cmd_rollback,
    }[args.cmd](args)


if __name__ == "__main__":
    main()
