"""
Generate dogs.json for DogQuest.
Uses Wikimedia Commons thumb.php for images.
"""
import json

# Dog breeds with real data
# Schema matches Bird.fromJson: name, scientificName, imageUrl, audioUrl, lore, habitat, conservationStatus, rarity, baseXp
# For dogs: scientificName = breed group, habitat = origin country, conservationStatus = popularity tier

dogs = [
    # ── COMMON (most popular, easily recognized) ──────────────────────────
    {"name": "Labrador Retriever", "scientificName": "Canis lupus familiaris", "group": "Sporting", "origin": "Canada", "lore": "The world's most popular dog breed for over 30 years. Originally bred to help fishermen haul nets and catch fish in icy waters.", "rarity": "common", "baseXp": 20, "image": "Labrador_Retriever_yellow.jpg"},
    {"name": "German Shepherd", "scientificName": "Canis lupus familiaris", "group": "Herding", "origin": "Germany", "lore": "Renowned for intelligence and versatility. Serves as police dogs, guide dogs, and search-and-rescue heroes worldwide.", "rarity": "common", "baseXp": 25, "image": "German_Shepherd_Dog_Alsatian.jpg"},
    {"name": "Golden Retriever", "scientificName": "Canis lupus familiaris", "group": "Sporting", "origin": "Scotland", "lore": "Bred by Lord Tweedmouth in the Scottish Highlands. Their gentle mouth can carry a raw egg without cracking it.", "rarity": "common", "baseXp": 20, "image": "Golden_Retriever_Carlos_%2810581910556%29.jpg"},
    {"name": "French Bulldog", "scientificName": "Canis lupus familiaris", "group": "Non-Sporting", "origin": "France", "lore": "Originally bred as miniature Bulldogs in England, they became wildly popular with Parisian lace workers in the 1800s.", "rarity": "common", "baseXp": 25, "image": "French_Bulldog_2022.jpg"},
    {"name": "Bulldog", "scientificName": "Canis lupus familiaris", "group": "Non-Sporting", "origin": "England", "lore": "Once bred for bull-baiting, today's Bulldog is a gentle couch potato. They're the mascot of the US Marine Corps.", "rarity": "common", "baseXp": 25, "image": "Bulldog_Tobias.jpg"},
    {"name": "Poodle", "scientificName": "Canis lupus familiaris", "group": "Non-Sporting", "origin": "Germany/France", "lore": "One of the most intelligent breeds. Their fancy haircuts originally served a practical purpose — keeping joints warm while swimming.", "rarity": "common", "baseXp": 25, "image": "Full_attention_%288067543690%29.jpg"},
    {"name": "Beagle", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "England", "lore": "Their incredible nose has 220 million scent receptors. Used by USDA at airports to sniff out contraband food.", "rarity": "common", "baseXp": 20, "image": "Beagle_600.jpg"},
    {"name": "Rottweiler", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "Germany", "lore": "Descended from Roman drover dogs. Butchers in Rottweil used them to pull carts of meat to market.", "rarity": "common", "baseXp": 30, "image": "Rottweiler_standing_facing_left.jpg"},
    {"name": "Yorkshire Terrier", "scientificName": "Canis lupus familiaris", "group": "Toy", "origin": "England", "lore": "Originally bred to catch rats in clothing mills. Despite tiny size, they have the heart of a terrier.", "rarity": "common", "baseXp": 20, "image": "Yorkshire_Terrier_2.jpg"},
    {"name": "Dachshund", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "Germany", "lore": "The 'sausage dog' was bred to hunt badgers underground. Their name literally means 'badger dog' in German.", "rarity": "common", "baseXp": 20, "image": "Dachshund_Lotta.jpg"},
    {"name": "Boxer", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "Germany", "lore": "Named for their habit of playing by standing on hind legs and 'boxing' with their front paws. Eternal puppies at heart.", "rarity": "common", "baseXp": 25, "image": "Boxer_female_brown.jpg"},
    {"name": "Siberian Husky", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "Siberia", "lore": "The Chukchi people bred them for endurance sled pulling. In 1925, Huskies ran a life-saving serum relay 674 miles to Nome, Alaska.", "rarity": "common", "baseXp": 30, "image": "Siberian_Husky_bi-eyed_Flickr.jpg"},
    {"name": "Cavalier King Charles Spaniel", "scientificName": "Canis lupus familiaris", "group": "Toy", "origin": "England", "lore": "Named after King Charles II, who was so devoted to them that he decreed they be allowed in any public place, including Parliament.", "rarity": "common", "baseXp": 25, "image": "Cavalier_King_Charles_Spaniel_trio.jpg"},
    {"name": "Doberman Pinscher", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "Germany", "lore": "Created by tax collector Louis Dobermann who wanted a loyal guard dog. One of the smartest and most trainable breeds.", "rarity": "common", "baseXp": 30, "image": "Dobermann_handling.jpg"},
    {"name": "Great Dane", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "Germany", "lore": "Despite their name, they're German, not Danish. The tallest dog ever recorded was a Great Dane named Zeus at 44 inches.", "rarity": "common", "baseXp": 30, "image": "Great_Dane_black_white.jpg"},
    {"name": "Australian Shepherd", "scientificName": "Canis lupus familiaris", "group": "Herding", "origin": "United States", "lore": "Despite the name, they were developed in the American West. Rodeo performers made them famous with incredible trick routines.", "rarity": "common", "baseXp": 25, "image": "Australian_Shepherd_red_merle.jpg"},
    {"name": "Miniature Schnauzer", "scientificName": "Canis lupus familiaris", "group": "Terrier", "origin": "Germany", "lore": "Bred down from Standard Schnauzers crossed with Poodles. Their distinctive beard and eyebrows give them a wise, old-man look.", "rarity": "common", "baseXp": 20, "image": "Miniature_Schnauzer.jpg"},
    {"name": "Pembroke Welsh Corgi", "scientificName": "Canis lupus familiaris", "group": "Herding", "origin": "Wales", "lore": "Queen Elizabeth II owned over 30 Corgis during her lifetime. Welsh legend says fairies rode them into battle.", "rarity": "common", "baseXp": 25, "image": "Welsh_Corgi_Pembroke.jpg"},
    {"name": "Shih Tzu", "scientificName": "Canis lupus familiaris", "group": "Toy", "origin": "China/Tibet", "lore": "Bred as palace pets for Chinese emperors. Their name means 'lion dog' and they were treasured as living hot water bottles.", "rarity": "common", "baseXp": 20, "image": "Shih-Tzu.jpg"},
    {"name": "Cocker Spaniel", "scientificName": "Canis lupus familiaris", "group": "Sporting", "origin": "England", "lore": "Named for their skill hunting woodcock. The inspiration for Lady in Disney's 'Lady and the Tramp.'", "rarity": "common", "baseXp": 20, "image": "English_Cocker_Spaniel_4.jpg"},
    {"name": "Pomeranian", "scientificName": "Canis lupus familiaris", "group": "Toy", "origin": "Pomerania", "lore": "Descended from large sled-pulling Spitz dogs. Queen Victoria's tiny Pomeranian sparked a craze for breeding them smaller.", "rarity": "common", "baseXp": 20, "image": "Pomeranian_orange-sable_Coco.jpg"},
    {"name": "Chihuahua", "scientificName": "Canis lupus familiaris", "group": "Toy", "origin": "Mexico", "lore": "The world's smallest dog breed, named after the Mexican state. Ancient Aztecs believed they guided souls through the underworld.", "rarity": "common", "baseXp": 20, "image": "Chihuahua1_bvdb.jpg"},
    {"name": "Border Collie", "scientificName": "Canis lupus familiaris", "group": "Herding", "origin": "Scotland/England", "lore": "Widely considered the most intelligent dog breed. Chaser, a Border Collie, learned the names of over 1,000 objects.", "rarity": "common", "baseXp": 25, "image": "Border_Collie_600.jpg"},
    {"name": "Pug", "scientificName": "Canis lupus familiaris", "group": "Toy", "origin": "China", "lore": "Ancient Chinese emperors prized Pugs so much they were guarded by soldiers. Their wrinkles were bred to form the Chinese character for 'prince.'", "rarity": "common", "baseXp": 20, "image": "Pug_600.jpg"},
    {"name": "Maltese", "scientificName": "Canis lupus familiaris", "group": "Toy", "origin": "Malta", "lore": "One of the oldest toy breeds, dating back over 2,000 years. Ancient Greeks built tombs for their beloved Maltese.", "rarity": "common", "baseXp": 20, "image": "Maltese_600.jpg"},

    # ── UNCOMMON (recognized but less frequently seen) ─────────────────────
    {"name": "Bernese Mountain Dog", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "Switzerland", "lore": "Swiss farm dogs that pulled milk carts through Alpine villages. One of four Swiss mountain dog breeds, and the only one with long hair.", "rarity": "uncommon", "baseXp": 35, "image": "Berner_Sennenhund_Flickr.jpg"},
    {"name": "Weimaraner", "scientificName": "Canis lupus familiaris", "group": "Sporting", "origin": "Germany", "lore": "The 'Gray Ghost' was bred for hunting large game like boar and deer. Their striking silver-gray coat and amber eyes are unmistakable.", "rarity": "uncommon", "baseXp": 35, "image": "Weimaraner_wb.jpg"},
    {"name": "Rhodesian Ridgeback", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "South Africa", "lore": "Originally bred to track lions in Africa. The distinctive ridge on their back is formed by hair growing in the opposite direction.", "rarity": "uncommon", "baseXp": 40, "image": "Rhodesian_ridgeback.jpg"},
    {"name": "Akita", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "Japan", "lore": "The legendary Hachiko waited for his deceased owner at a Tokyo train station every day for nearly 10 years. A national treasure of Japan.", "rarity": "uncommon", "baseXp": 40, "image": "Akita_inu.jpg"},
    {"name": "Dalmatian", "scientificName": "Canis lupus familiaris", "group": "Non-Sporting", "origin": "Croatia", "lore": "Born pure white, they develop their spots as they grow. Historically ran alongside horse-drawn fire carriages to guard the equipment.", "rarity": "uncommon", "baseXp": 30, "image": "Dalmatian_liver_bicolor.jpg"},
    {"name": "Whippet", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "England", "lore": "Can reach 35 mph in seconds, making them the fastest accelerating dog breed. Known as the 'poor man's racehorse.'", "rarity": "uncommon", "baseXp": 30, "image": "Whippet_white.jpg"},
    {"name": "Irish Setter", "scientificName": "Canis lupus familiaris", "group": "Sporting", "origin": "Ireland", "lore": "Their gorgeous mahogany coat made them show ring favorites. President Nixon's Irish Setter, King Timahoe, lived in the White House.", "rarity": "uncommon", "baseXp": 30, "image": "Irish_Setter_in_Tallinn.jpg"},
    {"name": "Samoyed", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "Siberia", "lore": "The Samoyede people slept with these dogs for warmth in -60F temperatures. Their permanent smile prevents drooling that would form icicles.", "rarity": "uncommon", "baseXp": 35, "image": "Samoyed_600.jpg"},
    {"name": "Bull Terrier", "scientificName": "Canis lupus familiaris", "group": "Terrier", "origin": "England", "lore": "Bred from Bulldogs and terriers for dog fighting, now beloved clowns. General Patton's Bull Terrier, Willie, accompanied him through WWII.", "rarity": "uncommon", "baseXp": 30, "image": "Bull_Terrier_Flickr.jpg"},
    {"name": "Basset Hound", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "France", "lore": "Their droopy ears sweep scent off the ground toward their nose. Second only to Bloodhounds in tracking ability.", "rarity": "uncommon", "baseXp": 30, "image": "Basset_hound_portrait.jpg"},
    {"name": "Staffordshire Bull Terrier", "scientificName": "Canis lupus familiaris", "group": "Terrier", "origin": "England", "lore": "Known as the 'nanny dog' in England for their gentle patience with children. Incredibly loyal and affectionate despite their tough appearance.", "rarity": "uncommon", "baseXp": 30, "image": "Staffordshire_Bull_Terrier_600.jpg"},
    {"name": "Shetland Sheepdog", "scientificName": "Canis lupus familiaris", "group": "Herding", "origin": "Scotland", "lore": "Miniature Collies from the Shetland Islands. They're so eager to please that they consistently rank among the top breeds in obedience competitions.", "rarity": "uncommon", "baseXp": 30, "image": "Shetland_Sheepdog_600.jpg"},
    {"name": "Vizsla", "scientificName": "Canis lupus familiaris", "group": "Sporting", "origin": "Hungary", "lore": "Hungary's national dog, called the 'Velcro Vizsla' for their need to be constantly touching their owner. Ancient Magyar warriors hunted with them.", "rarity": "uncommon", "baseXp": 35, "image": "Vizsla_600.jpg"},
    {"name": "Bichon Frise", "scientificName": "Canis lupus familiaris", "group": "Non-Sporting", "origin": "France/Belgium", "lore": "Renaissance royalty adored them. After the French Revolution, they survived by performing tricks as circus dogs.", "rarity": "uncommon", "baseXp": 25, "image": "Bichon_Frise_600.jpg"},
    {"name": "Airedale Terrier", "scientificName": "Canis lupus familiaris", "group": "Terrier", "origin": "England", "lore": "The 'King of Terriers' — largest of all terrier breeds. Served as messenger dogs and sentries in both World Wars.", "rarity": "uncommon", "baseXp": 35, "image": "Airedale_Terrier.jpg"},
    {"name": "Belgian Malinois", "scientificName": "Canis lupus familiaris", "group": "Herding", "origin": "Belgium", "lore": "The elite military working dog. Cairo, a Malinois, was part of the SEAL Team Six raid on Osama bin Laden.", "rarity": "uncommon", "baseXp": 40, "image": "Malinois_Flickr.jpg"},
    {"name": "Bloodhound", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "Belgium/France", "lore": "Can follow a scent trail over 300 hours old. Their trailing evidence is admissible in court — the only breed with this distinction.", "rarity": "uncommon", "baseXp": 35, "image": "Bloodhound_Erwin.jpg"},
    {"name": "English Springer Spaniel", "scientificName": "Canis lupus familiaris", "group": "Sporting", "origin": "England", "lore": "Named for their ability to 'spring' game from hiding. They can work tirelessly in the field all day and cuddle all evening.", "rarity": "uncommon", "baseXp": 30, "image": "English_Springer_Spaniel_liver_and_white.jpg"},
    {"name": "Cane Corso", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "Italy", "lore": "Ancient Roman war dog descended from the Molossus. Their name means 'guardian dog' in Latin. Nearly went extinct in the 1970s.", "rarity": "uncommon", "baseXp": 40, "image": "Cane_Corso_Flickr.jpg"},
    {"name": "Newfoundland", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "Canada", "lore": "Born to swim — they have webbed feet and a water-resistant coat. A Newfoundland is credited with saving Napoleon Bonaparte from drowning.", "rarity": "uncommon", "baseXp": 35, "image": "Newfoundland_dog_Smoky.jpg"},
    {"name": "Papillon", "scientificName": "Canis lupus familiaris", "group": "Toy", "origin": "France/Belgium", "lore": "Named for their butterfly-like ears ('papillon' is French for butterfly). Marie Antoinette reportedly walked to the guillotine carrying her Papillon.", "rarity": "uncommon", "baseXp": 25, "image": "Papillon_Flickr.jpg"},
    {"name": "Saint Bernard", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "Switzerland", "lore": "Alpine rescue dogs that saved over 2,000 travelers in the Swiss Alps. Barry, the most famous, rescued over 40 people.", "rarity": "uncommon", "baseXp": 35, "image": "Saint_Bernard_dog_2.jpg"},
    {"name": "Alaskan Malamute", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "Alaska", "lore": "One of the oldest Arctic sled dogs, bred by the Inuit Mahlemut people. Can pull loads up to 3,000 pounds.", "rarity": "uncommon", "baseXp": 35, "image": "Alaskan_Malamute.jpg"},
    {"name": "West Highland White Terrier", "scientificName": "Canis lupus familiaris", "group": "Terrier", "origin": "Scotland", "lore": "Bred white so hunters wouldn't mistake them for foxes. Their confident strut and perky ears make them one of the most recognizable terriers.", "rarity": "uncommon", "baseXp": 25, "image": "West_Highland_White_Terrier_Krakow.jpg"},
    {"name": "Jack Russell Terrier", "scientificName": "Canis lupus familiaris", "group": "Terrier", "origin": "England", "lore": "Named after Reverend John Russell, who bred them for fox hunting. Pound for pound, one of the most energetic dogs on Earth.", "rarity": "uncommon", "baseXp": 25, "image": "Jack_Russell_Terrier_2.jpg"},

    # ── RARE (distinctive, less commonly encountered) ──────────────────────
    {"name": "Afghan Hound", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "Afghanistan", "lore": "One of the oldest dog breeds, said to have been on Noah's Ark. Their flowing coat protected them in the harsh Afghan mountains.", "rarity": "rare", "baseXp": 50, "image": "Afghan_Hound.jpg"},
    {"name": "Irish Wolfhound", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "Ireland", "lore": "The tallest of all dog breeds. Ancient Irish laws only allowed kings and nobles to own them. They hunted wolves to extinction in Ireland.", "rarity": "rare", "baseXp": 55, "image": "Irish_Wolfhound.jpg"},
    {"name": "Borzoi", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "Russia", "lore": "Russian aristocracy bred them for wolf hunting. Leo Tolstoy immortalized them in 'War and Peace.' Can reach speeds of 40 mph.", "rarity": "rare", "baseXp": 50, "image": "Borzoi_600.jpg"},
    {"name": "Komondor", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "Hungary", "lore": "Their iconic corded coat makes them look like a giant mop, but it protects them from wolf bites while guarding sheep.", "rarity": "rare", "baseXp": 60, "image": "Komondor_delansen.jpg"},
    {"name": "Basenji", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "Central Africa", "lore": "The 'barkless dog' — they yodel instead of bark. Ancient Egyptians gave Basenjis as gifts to pharaohs. They groom themselves like cats.", "rarity": "rare", "baseXp": 50, "image": "Basenji_600.jpg"},
    {"name": "Xoloitzcuintli", "scientificName": "Canis lupus familiaris", "group": "Non-Sporting", "origin": "Mexico", "lore": "Over 3,000 years old, the ancient Aztec hairless dog. Named after the god Xolotl, who guided the dead. Considered national treasure of Mexico.", "rarity": "rare", "baseXp": 60, "image": "Xoloitzcuintli_600.jpg"},
    {"name": "Chinese Crested", "scientificName": "Canis lupus familiaris", "group": "Toy", "origin": "China/Africa", "lore": "Chinese sailors kept them on ships to hunt rats. The hairless variety has silky hair on head, tail, and feet — looking like a tiny punk rocker.", "rarity": "rare", "baseXp": 45, "image": "Chinese_Crested_Dog_600.jpg"},
    {"name": "Saluki", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "Middle East", "lore": "The 'Royal Dog of Egypt,' possibly the oldest domesticated breed. Mummified Salukis have been found in pharaohs' tombs.", "rarity": "rare", "baseXp": 55, "image": "Saluki_dog_breed.jpg"},
    {"name": "Tibetan Mastiff", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "Tibet", "lore": "Guardian of Himalayan monasteries. In 2014, a Tibetan Mastiff sold for $1.95 million in China, making it the most expensive dog ever sold.", "rarity": "rare", "baseXp": 60, "image": "Tibetan_Mastiff_Flickr.jpg"},
    {"name": "Pharaoh Hound", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "Malta", "lore": "National dog of Malta. One of the few breeds that can blush — their nose and ears turn rosy when excited.", "rarity": "rare", "baseXp": 55, "image": "Pharaoh_Hound.jpg"},
    {"name": "Norwegian Lundehund", "scientificName": "Canis lupus familiaris", "group": "Non-Sporting", "origin": "Norway", "lore": "Has six toes on each foot and can tip their head backward to touch their spine. Bred to hunt puffins on cliffsides.", "rarity": "rare", "baseXp": 55, "image": "Lundehund.jpg"},
    {"name": "Bedlington Terrier", "scientificName": "Canis lupus familiaris", "group": "Terrier", "origin": "England", "lore": "Looks like a lamb but hunts like a wolf. Originally bred by miners in Bedlington to catch rats and race for sport.", "rarity": "rare", "baseXp": 50, "image": "Bedlington_Terrier.jpg"},
    {"name": "Leonberger", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "Germany", "lore": "Created to resemble the lion on the city crest of Leonberg. Used as water rescue dogs thanks to their webbed feet and massive size.", "rarity": "rare", "baseXp": 50, "image": "Leonberger_male.jpg"},
    {"name": "Otterhound", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "England", "lore": "One of the rarest breeds — fewer than 800 exist worldwide. Their webbed feet and oily double coat made them perfect otter hunters.", "rarity": "rare", "baseXp": 60, "image": "Otterhound_600.jpg"},
    {"name": "Lagotto Romagnolo", "scientificName": "Canis lupus familiaris", "group": "Sporting", "origin": "Italy", "lore": "The world's only breed specifically bred for truffle hunting. Their curly, waterproof coat and exceptional nose make them truffle-finding machines.", "rarity": "rare", "baseXp": 50, "image": "Lagotto_Romagnolo.jpg"},
    {"name": "Azawakh", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "West Africa", "lore": "A Saharan sighthound from the Tuareg nomads. So lean that their bone structure is visible through their skin — built for desert heat.", "rarity": "rare", "baseXp": 60, "image": "Azawakh_Flickr.jpg"},
    {"name": "Bergamasco Sheepdog", "scientificName": "Canis lupus familiaris", "group": "Herding", "origin": "Italy", "lore": "Their coat naturally forms into felt-like mats that protect against weather and predators. Once set, it never needs brushing.", "rarity": "rare", "baseXp": 55, "image": "Bergamasco_Shepherd_Dog.jpg"},
    {"name": "Thai Ridgeback", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "Thailand", "lore": "One of only three ridgeback breeds. Isolated on Thai islands for centuries, they evolved independently and can even climb trees.", "rarity": "rare", "baseXp": 55, "image": "Thai_Ridgeback.jpg"},
    {"name": "Peruvian Inca Orchid", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "Peru", "lore": "Ancient Inca hairless dog considered magical. The Incas believed their body heat could cure arthritis and respiratory ailments.", "rarity": "rare", "baseXp": 55, "image": "Peruvian_Hairless_Dog.jpg"},
    {"name": "Mudi", "scientificName": "Canis lupus familiaris", "group": "Herding", "origin": "Hungary", "lore": "A rare Hungarian herding breed that can manage flocks of up to 500 sheep single-handedly. Also excels at hunting wild boar.", "rarity": "rare", "baseXp": 50, "image": "Mudi_600.jpg"},

    # ── LEGENDARY (extremely rare, exotic, or historically significant) ───
    {"name": "Catalburun", "scientificName": "Canis lupus familiaris", "group": "Sporting", "origin": "Turkey", "lore": "One of only three breeds with a split nose (double nose). Fewer than 200 exist outside Turkey. Exceptional pointer with incredible scent ability.", "rarity": "legendary", "baseXp": 80, "image": "Catalburun.jpg"},
    {"name": "New Guinea Singing Dog", "scientificName": "Canis hallstromi", "group": "Hound", "origin": "Papua New Guinea", "lore": "A wild canid only recently studied, known for their haunting, harmonic howl. Can climb trees and bend their spine like a cat.", "rarity": "legendary", "baseXp": 100, "image": "New_Guinea_Singing_Dog.jpg"},
    {"name": "Chinook", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "United States", "lore": "New Hampshire's state dog, bred by explorer Arthur Walden. Nearly went extinct with only 11 dogs left in 1981. A true American original.", "rarity": "legendary", "baseXp": 80, "image": "Chinook_dog.jpg"},
    {"name": "Telomian", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "Malaysia", "lore": "One of the rarest breeds. Malaysian indigenous people bred them to climb ladders to enter raised houses. Can grasp objects with their paws.", "rarity": "legendary", "baseXp": 100, "image": "Telomian.jpg"},
    {"name": "Carolina Dog", "scientificName": "Canis lupus familiaris", "group": "Hound", "origin": "United States", "lore": "America's own 'dingo' — feral dogs discovered in South Carolina's swamps. DNA suggests they crossed the Bering land bridge with ancient humans.", "rarity": "legendary", "baseXp": 80, "image": "Carolina_Dog.jpg"},
    {"name": "Kai Ken", "scientificName": "Canis lupus familiaris", "group": "Non-Sporting", "origin": "Japan", "lore": "A natural monument of Japan. Their brindle coat earned them the nickname 'Tiger Dog.' So rare that even in Japan, few have seen one.", "rarity": "legendary", "baseXp": 90, "image": "Kai_Ken.jpg"},
    {"name": "Stabyhoun", "scientificName": "Canis lupus familiaris", "group": "Sporting", "origin": "Netherlands", "lore": "One of the five rarest breeds in the world. Only about 7,000 exist globally. A versatile Dutch farm dog that excels at everything.", "rarity": "legendary", "baseXp": 90, "image": "Stabyhoun.jpg"},
    {"name": "Fila Brasileiro", "scientificName": "Canis lupus familiaris", "group": "Working", "origin": "Brazil", "lore": "So loyal that a Brazilian proverb says 'faithful as a Fila.' Bred to track escaped slaves and jaguars. Banned in several countries.", "rarity": "legendary", "baseXp": 80, "image": "Fila_Brasileiro.jpg"},
    {"name": "Canaan Dog", "scientificName": "Canis lupus familiaris", "group": "Herding", "origin": "Israel", "lore": "Descended from the pariah dogs of ancient Canaan. Used by the Israeli military as mine detectors and messengers.", "rarity": "legendary", "baseXp": 80, "image": "Canaan_Dog.jpg"},
    {"name": "Kooikerhondje", "scientificName": "Canis lupus familiaris", "group": "Sporting", "origin": "Netherlands", "lore": "Dutch duck decoying dogs that lured ducks into traps by wagging their fluffy white-tipped tails. A Kooiker allegedly saved William of Orange's life.", "rarity": "legendary", "baseXp": 85, "image": "Kooikerhondje_600.jpg"},
]

# Build the final JSON with proper image URLs
output = []
for dog in dogs:
    img_file = dog.pop("image")
    group = dog.pop("group")
    origin = dog.pop("origin")

    entry = {
        "name": dog["name"],
        "scientificName": f"{dog['scientificName']} ({group})",
        "imageUrl": f"https://commons.wikimedia.org/w/thumb.php?f={img_file}&w=400",
        "audioUrl": "",  # Dogs don't have audio identification
        "lore": dog["lore"],
        "habitat": f"{group} Group | Origin: {origin}",
        "conservationStatus": "Domesticated",
        "rarity": dog["rarity"],
        "baseXp": dog["baseXp"]
    }
    output.append(entry)

# Write JSON
with open("assets/dogs.json", "w", encoding="utf-8") as f:
    json.dump(output, f, indent=2, ensure_ascii=False)

# Write labels file (breed names for ML model)
with open("assets/dog_labels.txt", "w", encoding="utf-8") as f:
    for dog in output:
        f.write(dog["name"] + "\n")

print(f"Generated {len(output)} dog breeds")
print(f"  Common: {sum(1 for d in dogs if d['rarity'] == 'common')}")
print(f"  Uncommon: {sum(1 for d in dogs if d['rarity'] == 'uncommon')}")
print(f"  Rare: {sum(1 for d in dogs if d['rarity'] == 'rare')}")
print(f"  Legendary: {sum(1 for d in dogs if d['rarity'] == 'legendary')}")
