import { Ability, Attack, Card, getCardId } from "../types/card";

const CARDS_URL =
  "https://raw.githubusercontent.com/flibustier/pokemon-tcg-pocket-database/main/dist/cards.extra.json";

// Generated by scripts/fetch-rich-cards.mjs and committed to public/.
// Provides attacks + abilities keyed by cardId.
const RICH_URL = "/pokemon/cards-rich.json";

interface RichBundle {
  source: string;
  generatedAt: string;
  cards: Record<string, { attacks?: Attack[]; abilities?: Ability[] }>;
}

let cachedCards: Card[] | null = null;

export async function fetchCards(): Promise<Card[]> {
  if (cachedCards) return cachedCards;

  // Fetch both in parallel. The rich fetch is best-effort: if it fails,
  // we still return base cards with no attacks/abilities and the score /
  // auto-build modules degrade gracefully.
  const [baseRes, richRes] = await Promise.all([
    fetch(CARDS_URL),
    fetch(RICH_URL).catch(() => null),
  ]);
  if (!baseRes.ok) throw new Error(`Failed to fetch cards: ${baseRes.status}`);
  const base: Card[] = await baseRes.json();

  let rich: RichBundle["cards"] = {};
  if (richRes && richRes.ok) {
    try {
      const bundle: RichBundle = await richRes.json();
      rich = bundle.cards ?? {};
    } catch {
      // Malformed rich bundle — skip silently.
    }
  }

  const merged = base.map((c) => {
    const r = rich[getCardId(c)];
    return r ? { ...c, ...r } : c;
  });

  cachedCards = merged;
  return merged;
}

export function getCardById(cards: Card[], cardId: string): Card | undefined {
  const [set, numStr] = cardId.split("-");
  const number = parseInt(numStr, 10);
  return cards.find((c) => c.set === set && c.number === number);
}

export function getCardsByName(cards: Card[], name: string): Card[] {
  return cards.filter((c) => c.name.toLowerCase() === name.toLowerCase());
}

export function getSets(cards: Card[]): string[] {
  return [...new Set(cards.map((c) => c.set))];
}

export function getElements(cards: Card[]): string[] {
  return [...new Set(cards.filter((c) => c.element).map((c) => c.element!))];
}
