import { Ability, Attack, Card, getCardId } from "../types/card";
import { computeCapabilities } from "../utils/card-classifier";

const CARDS_URL =
  "https://raw.githubusercontent.com/flibustier/pokemon-tcg-pocket-database/main/dist/cards.extra.json";

// Generated by scripts/fetch-rich-cards.mjs and committed to public/.
// Provides attacks + abilities keyed by cardId.
const RICH_URL = "/pokemon/cards-rich.json";

interface RichBundle {
  source: string;
  generatedAt: string;
  cards: Record<string, { attacks?: Attack[]; abilities?: Ability[] }>;
}

let cachedCards: Card[] | null = null;
// Map<cardId, Card> built in lockstep with cachedCards so getCardById is
// O(1) instead of O(n). Same lifecycle as cachedCards — both are populated
// once on first fetchCards() and cached for the session.
let cachedIndex: Map<string, Card> | null = null;

export async function fetchCards(): Promise<Card[]> {
  if (cachedCards) return cachedCards;

  // Fetch both in parallel. The rich fetch is best-effort: if it fails,
  // we still return base cards with no attacks/abilities and the score /
  // auto-build modules degrade gracefully.
  const [baseRes, richRes] = await Promise.all([
    fetch(CARDS_URL),
    fetch(RICH_URL).catch(() => null),
  ]);
  if (!baseRes.ok) throw new Error(`Failed to fetch cards: ${baseRes.status}`);
  const base: Card[] = await baseRes.json();

  let rich: RichBundle["cards"] = {};
  if (richRes && richRes.ok) {
    try {
      const bundle: RichBundle = await richRes.json();
      rich = bundle.cards ?? {};
    } catch {
      // Malformed rich bundle — skip silently.
    }
  }

  // Single pass: merge rich-card data, compute capabilities, and build
  // the cardId index. All three derive from the same merged Card so the
  // pass cost is one allocation per card.
  const merged: Card[] = [];
  const index = new Map<string, Card>();
  for (const c of base) {
    const r = rich[getCardId(c)];
    const enrichedBase: Card = r ? { ...c, ...r } : c;
    const enriched: Card = {
      ...enrichedBase,
      capabilities: computeCapabilities(enrichedBase),
    };
    merged.push(enriched);
    index.set(getCardId(enriched), enriched);
  }

  cachedCards = merged;
  cachedIndex = index;
  return merged;
}

// O(1) cardId lookup via the merge-time index. The `_cards` argument is
// retained as a no-op so callers don't all need to change — the index is
// populated alongside cachedCards and shares the same lifecycle, so any
// caller holding a reference to the cards array also has the index.
export function getCardById(_cards: Card[], cardId: string): Card | undefined {
  return cachedIndex?.get(cardId);
}

export function getCardsByName(cards: Card[], name: string): Card[] {
  return cards.filter((c) => c.name.toLowerCase() === name.toLowerCase());
}

export function getSets(cards: Card[]): string[] {
  return [...new Set(cards.map((c) => c.set))];
}

export function getElements(cards: Card[]): string[] {
  return [...new Set(cards.filter((c) => c.element).map((c) => c.element!))];
}
